fieldLayouts:
  0c7bba1a-e1c8-46ce-b9f4-c683eeb2608e:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 8bcf8e26-bb4b-465f-8899-14c0392016a5
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: e38caed8-3877-4f70-8c75-49196e81c138
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: f0f80de8-a5f6-4cda-bed0-f5dbeb6c3efd
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 5cb5b657-4a4a-423c-b66f-cb4f977e52b7
            required: true
            type: craft\fieldlayoutelements\CustomField
        name: About
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 1e5542a7-3a38-49b2-b143-164d56576e5e
            required: true
            type: craft\fieldlayoutelements\CustomField
        name: Services
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 22f8350d-7c98-489d-b879-07b22f013ec4
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 269cf768-5324-4368-830b-6d443834d7a7
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 2fc56fad-3168-441e-bb3b-ec743dab75b4
            required: true
            type: craft\fieldlayoutelements\CustomField
        name: Team
        sortOrder: 3
      -
        elements:
          -
            fieldUid: 51ece176-0c0f-4e07-9e1a-a0fae04bc709
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: afdbb43e-c582-4fff-ad0b-7e0ad5cda3fa
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 4
handle: about
hasTitleField: false
name: About
section: 2a8e2a68-0941-47c3-9c48-27b6e98ed681
sortOrder: 1
titleFormat: '{section.name|raw}'
