fieldLayouts:
  83caa409-c7ef-4606-a957-cfbd779a784f:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: fef300bb-fd16-4af0-b3c3-ee86610e1575
            required: true
            type: craft\fieldlayoutelements\CustomField
        name: Home
        sortOrder: 1
handle: home
hasTitleField: false
name: Home
section: b45ca5c2-238c-4d66-a136-9eb0782c1092
sortOrder: 1
titleFormat: '{section.name|raw}'
