fieldLayouts:
  c6eba272-3b3c-4db3-abe4-c5aa074cd430:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 51ece176-0c0f-4e07-9e1a-a0fae04bc709
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: afdbb43e-c582-4fff-ad0b-7e0ad5cda3fa
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 1
handle: news
hasTitleField: false
name: News
section: 4a933c3d-f2d2-4e10-9092-bfb44e4eff56
sortOrder: 1
titleFormat: '{section.name|raw}'
