fieldLayouts:
  77c40cc5-2085-4b9c-93d7-711119d2b137:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 7c23c6a2-2d1f-4075-bd33-735bca061a49
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: f9600254-bff1-40e1-80ee-b62c111ae1ba
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 5f66a1dd-2265-4569-9d80-5f8a7d596ebd
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 535ac877-b8f6-4d1e-b3f0-0d7414c38954
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 2cc951e2-4ee9-4241-9c48-ffafc42009d2
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Details
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 28f90f10-bb72-45ab-a269-b357da662c63
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 492a166c-ca7b-4314-97a6-555896c1a9b1
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 092722e8-7b2f-438a-b147-07019a7883dd
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Images
        sortOrder: 2
      -
        elements:
          -
            fieldUid: e8b892e0-1298-4063-ae18-e8ddf8f24c94
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: e6a3f05c-8408-49ff-8373-fb2292c13450
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Placements
        sortOrder: 3
      -
        elements:
          -
            fieldUid: 51ece176-0c0f-4e07-9e1a-a0fae04bc709
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: afdbb43e-c582-4fff-ad0b-7e0ad5cda3fa
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 4
handle: projectPages
hasTitleField: true
name: 'Project Pages'
section: 1a2a7c95-1089-4cf8-abf3-ac2f6eb47665
sortOrder: 1
titleFormat: ''
