contentColumnType: text
fieldGroup: 39826311-1380-4080-b915-84461fe6689f
handle: phoneNumber
instructions: ''
name: 'Phone Number'
searchable: false
settings:
  charLimit: '14'
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
