contentColumnType: text
fieldGroup: 39826311-1380-4080-b915-84461fe6689f
handle: studioAddress
instructions: ''
name: 'Studio Address'
searchable: true
settings:
  charLimit: ''
  code: ''
  columnType: text
  initialRows: '2'
  multiline: '1'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
