enableVersioning: true
handle: newsPosts
name: 'News Posts'
propagationMethod: all
siteSettings:
  c61833c8-0611-48fe-89ba-399962d57890:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: ''
type: channel
